### ISSUE TITLE
 Error installing sass

### ISSUE THREAD

**Issue by wadie** [tliron/install-gnome-themes#14]
> ERROR:  Error installing sass:
	ERROR: Failed to build gem native extension.

>    current directory: /var/lib/gems/2.3.0/gems/ffi-1.9.18/ext/ffi_c
/usr/bin/ruby2.3 -r ./siteconf20170714-4219-9qk1ng.rb extconf.rb

> mkmf.rb can't find header files for ruby at /usr/lib/ruby/include/ruby.h

> extconf failed, exit code 1

Any ideas ?

**Comment by tliron** [comment]
It seems that ruby gems are broken on your system. What is the OS?

**Comment by HarlemSquirrel** [comment]
Installing gems with sudo is not a great idea. 

Try this
```sh
sudo apt install ruby-dev
export PATH="$(ruby -rubygems -e 'puts Gem.user_dir')/bin:$PATH"
gem install --user-install sass
```
