### ISSUE TITLE
For me it gives me that on Ubuntu Gnome 16.4

### ISSUE THREAD

**Issue by meuor** [tliron/install-gnome-themes#16]
ragay@gino:~/install-gnome-themes$ ./install-gnome-themes 
Detected GNOME 3.18, GTK 3.18.
Detected Ubuntu operating system.
Verifying that build requirements are installed...
[sudo] password for ragay: 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Package 'numix-gtk-theme' is not installed, so not removed
The following package was automatically installed and is no longer required:
  snap-confine
Use 'sudo apt autoremove' to remove it.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Reading package lists... Done
Building dependency tree       
Reading state information... Done
autoconf is already the newest version (2.69-9).
automake is already the newest version (1:1.15-4ubuntu1).
inkscape is already the newest version (0.91-7ubuntu2).
librsvg2-dev is already the newest version (2.40.13-3).
pkg-config is already the newest version (0.29.1-0ubuntu1).
ruby is already the newest version (1:2.3.0+1).
fonts-noto-hinted is already the newest version (20160116-1).
fonts-roboto-hinted is already the newest version (2:0~20160106-1).
gnome-themes-standard is already the newest version (3.18.0-2ubuntu1).
parallel is already the newest version (20141022+ds1-1).
ruby-bundler is already the newest version (1.11.2-1).
git is already the newest version (1:2.7.4-0ubuntu1.1).
gtk2-engines-murrine is already the newest version (0.98.2-0ubuntu2.2).
libgdk-pixbuf2.0-dev is already the newest version (2.32.2-1ubuntu1.2).
libglib2.0-bin is already the newest version (2.48.2-0ubuntu1).
libglib2.0-dev is already the newest version (2.48.2-0ubuntu1).
libgtk-3-dev is already the newest version (3.18.9-1ubuntu3.3).
libxml2-utils is already the newest version (2.9.3+dfsg1-1ubuntu0.2).
gtk2-engines-pixbuf is already the newest version (2.24.30-1ubuntu1.16.04.1).
The following package was automatically installed and is no longer required:
  snap-confine
Use 'sudo apt autoremove' to remove it.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Building native extensions.  This could take a while...
ERROR:  Error installing sass:
	ERROR: Failed to build gem native extension.

    current directory: /var/lib/gems/2.3.0/gems/ffi-1.9.18/ext/ffi_c
/usr/bin/ruby2.3 -r ./siteconf20170714-3431-c97fhs.rb extconf.rb
mkmf.rb can't find header files for ruby at /usr/lib/ruby/include/ruby.h

extconf failed, exit code 1

Gem files will remain installed in /var/lib/gems/2.3.0/gems/ffi-1.9.18 for inspection.
Results logged to /var/lib/gems/2.3.0/extensions/x86_64-linux/2.3.0/ffi-1.9.18/gem_make.out

**Comment by nolt** [comment]
Same here, cant rebuild themes:

WARNING:  You don't have /home/***/.gem/ruby/2.3.0/bin in your PATH,
	  gem executables will not run.
Building native extensions.  This could take a while...
ERROR:  Error installing sass:
	ERROR: Failed to build gem native extension.

    current directory: /home/***/.gem/ruby/2.3.0/gems/ffi-1.9.18/ext/ffi_c
/usr/bin/ruby2.3 -r ./siteconf20170722-17905-72h96a.rb extconf.rb
mkmf.rb can't find header files for ruby at /usr/lib/ruby/include/ruby.h

extconf failed, exit code 1

Gem files will remain installed in /home/***/.gem/ruby/2.3.0/gems/ffi-1.9.18 for inspection.
Results logged to /home/***/.gem/ruby/2.3.0/extensions/x86_64-linux/2.3.0/ffi-1.9.18/gem_make.out

**Comment by tliron** [comment]
I think we were missing a package. Can you pull and try again?

**Comment by nolt** [comment]
After pull and trying to build got this one:

WARNING:  You don't have /home/***/.gem/ruby/2.3.0/bin in your PATH,
	  gem executables will not run.
ERROR:  While executing gem ... (Errno::EACCES)
    Permission denied @ rb_sysopen - /home/***/.gem/ruby/2.3.0/gems/ffi-1.9.18/COPYING

**Comment by tliron** [comment]
It doesn't make sense to me that you get a "permission denied" error while accessing your own home directory. Could you check the permissions on those directories?

**Comment by nolt** [comment]
I'm confused this directory  /home/***/.gem/ruby/2.3.0/gems/ffi-1.9.18 was owned by root:root. After chmod -R to user:user permission, installation has been continued only with previous warrning:
WARNING: You don't have /home/***/.gem/ruby/2.3.0/bin in your PATH,
gem executables will not run

:+1:

**Comment by meuor** [comment]
It worked Now well on Debian Gnome scratch
