### ISSUE TITLE
Add support for Elementary OS

### ISSUE THREAD

**Issue by afecelis** [tliron/install-gnome-themes#19]
When I run the script I get the following error:
`This script currently only supports Debian, Ubuntu, and LinuxMint. `
Elementary is based on Ubuntu 16.04 and should be compatible.

**Comment by tliron** [comment]
Could you try to submit a fix perhaps? It indeed should work.

**Comment by tliron** [comment]
I have removed all OS-specific code from the script as it was getting unmanageable. Instructions are now provided in the README.
