### ISSUE TITLE
Themes don't apply

### ISSUE THREAD

**Issue by Dennis4720** [tliron/install-gnome-themes#20]
After running the script and all of the themes were installed they are not visible at the gnome tweak tool.

I've editted Debian to Kali in the source so it'd run.

**Comment by Dennis4720** [comment]
No reaction?

**Comment by tliron** [comment]
Sorry, I somehow missed this. Are you sure you have the User Themes
extension installed?

**Comment by Dennis4720** [comment]
Looks like i didn't. Thanks for your help!

**Comment by tliron** [comment]
I will add a comment on this in the README. Thank you for taking time to
report the issue!
