### ISSUE TITLE
Ubuntu 18.04 install issues 

### ISSUE THREAD

**Issue by Erurainon** [tliron/install-gnome-themes#23]
Traceback (most recent call last):
	1: from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
/usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require': cannot load such file -- ubygems (LoadError)
Adapta, Adapta-Eta, Adapta-Nokto, Adapta-Nokto-Eta:
  Fetching repository: https://github.com/tista500/Adapta...
  Last updated 2 days ago. 
  Installing... 
  WARNING: Installation takes an especially long time due to rendering of all assets, please be patient!

**Comment by tliron** [comment]
See the `install-requirements-debian` file. Are you sure you installed the gem?

**Comment by Erurainon** [comment]
yes i did  install-requirements-debian

**Comment by Erurainon** [comment]
gem install --user-install sass
WARNING:  You don't have /home/muggle/.gem/ruby/2.5.0/bin in your PATH,
	  gem executables will not run.
Successfully installed sass-3.5.6
Parsing documentation for sass-3.5.6
Done installing documentation for sass after 2 seconds
1 gem installed

**Comment by Erurainon** [comment]
./install-requirements-debian 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
autoconf is already the newest version (2.69-11).
automake is already the newest version (1:1.15.1-3ubuntu2).
git is already the newest version (1:2.17.0-1ubuntu1).
gtk2-engines-murrine is already the newest version (0.98.2-2ubuntu1).
gtk2-engines-pixbuf is already the newest version (2.24.32-1ubuntu1).
libgdk-pixbuf2.0-dev is already the newest version (2.36.11-2).
libglib2.0-bin is already the newest version (2.56.1-2ubuntu1).
libglib2.0-dev is already the newest version (2.56.1-2ubuntu1).
libgtk-3-dev is already the newest version (3.22.29-3ubuntu1).
librsvg2-dev is already the newest version (2.40.20-2).
libxml2-utils is already the newest version (2.9.4+dfsg1-6.1ubuntu1).
optipng is already the newest version (0.7.6-1.1).
pkg-config is already the newest version (0.29.1-0ubuntu2).
ruby is already the newest version (1:2.5.1).
ruby-dev is already the newest version (1:2.5.1).
fonts-noto-hinted is already the newest version (20171026-2).
fonts-roboto-hinted is already the newest version (2:0~20160106-2).
gnome-themes-standard is already the newest version (3.28-1ubuntu1).
inkscape is already the newest version (0.92.3-1).
parallel is already the newest version (20161222-1).
ruby-bundler is already the newest version (1.16.1-1).
sassc is already the newest version (3.4.5-1).
The following packages were automatically installed and are no longer required:
  augeas-lenses cpu-checker ibverbs-providers ipxe-qemu
  ipxe-qemu-256k-compat-efi-roms libaio1 libaugeas0 libcacard0 libfdt1
  libgovirt-common libgovirt2 libgtk-vnc-2.0-0 libgvnc-1.0-0 libibverbs1
  libiscsi7 libnetcf1 libnl-route-3-200 libosinfo-bin libphodav-2.0-0
  libphodav-2.0-common librados2 librbd1 librdmacm1 libspice-client-glib-2.0-8
  libspice-client-gtk-3.0-5 libspice-server1 libusbredirhost1
  libusbredirparser1 libvirt-daemon libvirt-daemon-driver-storage-rbd
  libvirt-glib-1.0-0 libvirt0 libxen-4.9 libxenstore3.0 msr-tools
  qemu-block-extra qemu-kvm qemu-system-common qemu-system-x86 qemu-utils
  seabios spice-client-glib-usb-acl-helper
Use 'sudo apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
WARNING:  You don't have /home/muggle/.gem/ruby/2.5.0/bin in your PATH,
	  gem executables will not run.
Successfully installed sass-3.5.6
Parsing documentation for sass-3.5.6
Done installing documentation for sass after 2 seconds
1 gem installed
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Package 'numix-gtk-theme' is not installed, so not removed
The following packages were automatically installed and are no longer required:
  augeas-lenses cpu-checker ibverbs-providers ipxe-qemu
  ipxe-qemu-256k-compat-efi-roms libaio1 libaugeas0 libcacard0 libfdt1
  libgovirt-common libgovirt2 libgtk-vnc-2.0-0 libgvnc-1.0-0 libibverbs1
  libiscsi7 libnetcf1 libnl-route-3-200 libosinfo-bin libphodav-2.0-0
  libphodav-2.0-common librados2 librbd1 librdmacm1 libspice-client-glib-2.0-8
  libspice-client-gtk-3.0-5 libspice-server1 libusbredirhost1
  libusbredirparser1 libvirt-daemon libvirt-daemon-driver-storage-rbd
  libvirt-glib-1.0-0 libvirt0 libxen-4.9 libxenstore3.0 msr-tools
  qemu-block-extra qemu-kvm qemu-system-common qemu-system-x86 qemu-utils
  seabios spice-client-glib-usb-acl-helper
Use 'sudo apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

**Comment by tliron** [comment]
Cool. Can you please run this command and tell me the output?

    ruby -rubygems -e 'puts Gem.user_dir'

**Comment by Erurainon** [comment]
~/install-gnome-themes$ ruby -rubygems -e 'puts Gem.user_dir'
Traceback (most recent call last):
	1: from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
/usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require': cannot load such file -- ubygems (LoadError)

**Comment by tliron** [comment]
I can't read your post properly. Please use ``` lines before and after your code paste. See the [instructions](https://guides.github.com/features/mastering-markdown/).

**Comment by ghost** [comment]
The flag `-rubygems` was deprecated. See the [upstream bug](https://bugs.ruby-lang.org/issues/14322).
Just remove it to fix the error.

`ruby -e 'puts Gem.user_dir'`

**Comment by tliron** [comment]
It was not just deprecated, it was removed. :)

Thank you so much for your research! I have committed a fix for this and closing the issue. Please reopen if it's still causing problems.

I'm also fixing the requirements installation to recommend using the OSes sass package. You really need to do a manual install of the Ruby gem only for very old OSes.

**Comment by Erurainon** [comment]
Okay so I've manual install RUBY, ran ./install-sassc then ./install-requirements-debian, and run the ./install-gnome-theme and seems that it's installing now. Thanks for your time and help.
