### ISSUE TITLE
Moving to Gitlab

### ISSUE THREAD

**Issue by ghost** [tliron/install-gnome-themes#25]
Hi.
Would you consider moving to gitlab?
Seems like a lot of projects are moving after Microsoft announced they bought Github.

**Comment by tliron** [comment]
I am definitely considering it and I have a bunch of projects on GitLab already.

For now I am in a "wait and see" mode. Microsoft has a terrible track record with the open source community, but it's possible they will do a good job here.

Keeping this issue open for now. :)

**Comment by ghost** [comment]
Thanks for the update.
If you decide to move, I will contribute over there.

**Comment by tliron** [comment]
Understood. I am in the process of creating a mirror there, but right now GitLab is very overloaded for some reason. ;)

**Comment by tliron** [comment]
Please feel free to use the mirror on GitLab: https://gitlab.com/emblemparade/install-gnome-themes

**Comment by tliron** [comment]
Looks like the GitLab project was created as private by default. It should be public now.
