### ISSUE TITLE
problem with installing themes

### ISSUE THREAD

**Issue by sargis-tovmasyan** [tliron/install-gnome-themes#26]
after ./isntall-gnome-themes, getting this message:

Detected GNOME 3.22, GTK 3.22.
Detected Debian operating system.
Adapta, Adapta-Eta, Adapta-Nokto, Adapta-Nokto-Eta:
  Fetching repository: https://github.com/tista500/Adapta...
  Last updated 3 недели назад. 
  Installing... 
  WARNING: Installation takes an especially long time due to rendering of all assets, please be patient! 

*****************************************************************************************************
Looks like problem with some theme packs (adapta,pocillo and some) skiped them on the script and all other was installed, please lookup whats wrong with them.

**Comment by tliron** [comment]
Can you run this and see what's in the logs?
```
LOG=/dev/stdout ./install-gnome-themes
```

**Comment by sargis-tovmasyan** [comment]
`Gtk-Message: Failed to load module "canberra-gtk-module" `

many times
and this

> Meson encountered an error in file meson.build, line 1, column 0:
> Not enough arguments to project(). Needs at least the project name and one language


**************************************
by the way now adapta and pocillo was installed!

**Comment by tliron** [comment]
Have you installed all the requirements? It looks like canberra is not installed and is needed.
I don't have a Debian install handy, so I would appreciate help in debugging this!

**Comment by sargis-tovmasyan** [comment]
I already installed the recommended but checked and the Canberra was not installed, installed it and launch again, waiting for the end. may be add on requirements Canberra? checked it's not there!

**Comment by tliron** [comment]
Thanks! Yes, I see it's not installed. I guess it already preinstalled on many systems, but we should force it. Could you possibly submit a pull request with the fix?

**Comment by sargis-tovmasyan** [comment]
Yaru:
  Fetching repository: https://github.com/ubuntu/yaru...
Клонирование в «yaru»…
remote: Enumerating objects: 4354, done.
remote: Counting objects: 100% (4354/4354), done.
remote: Compressing objects: 100% (3958/3958), done.
remote: Total 4354 (delta 509), reused 3979 (delta 374), pack-reused 0
Получение объектов: 100% (4354/4354), 20.32 MiB | 317.00 KiB/s, готово.
Определение изменений: 100% (509/509), готово.
  Last updated 10 дней назад. 
  Installing... 
The Meson build system
Version: 0.37.1
Source dir: /tmp/install-gnome-themes/yaru
Build dir: /tmp/install-gnome-themes/yaru/_build
Build type: native build

Meson encountered an error in file meson.build, line 1, column 0:
Not enough arguments to project(). Needs at least the project name and one language
***************************
now something wrong with yaru :) btw ty man help me so :+1:

**Comment by Saqo1995s** [comment]
now something wrong with yaru :) btw ty man help me so :+1:

**Comment by sargis-tovmasyan** [comment]
ok i will pul it!

**Comment by sargis-tovmasyan** [comment]
pull request ready, but now yaru don't installing. (i don't need it, just asking you to know, alredy posted error message!)
