### ISSUE TITLE
Ability to select themes

### ISSUE THREAD

**Issue by Findarato** [tliron/install-gnome-themes#30]
It would be nice to have an option to allow for toggling themes off and on from a configuration file.  Default to them all on, but a simple bash variable file to turn them on / off would be nice. 

```bash
#!/bin/bash

Adapta=true
AdwaitaTweaks=true
Amber=true
Ant=true
```

This is an example of what I am referring to. By defaulting them all on, nothing would be broken from the default action, but if a user wanted to only install one, or to install all but a few it would work.

**Comment by tliron** [comment]
Not a bad idea. I think the best place for this would be the `~/.themes/.install-gnome-themes` file. There could be a special entry there to block it off. Will look into it.

**Comment by tliron** [comment]
Thank you for your patience in waiting for this to be implemented! See the README for how to use it:
```
To avoid rebuilding themes if there was no change the script caches identifiers in the file
`.install-gnome-themes.conf` in the current user's `.themes` folder. Delete it to force rebuilding
all themes:

    rm ~/.themes/.install-gnome-themes.conf

You can also edit this file to skip themes. Just put the word "skip" instead of the git hash. For
example, to skip Plano themes:

    github|lassekongo83|plano-theme|master skip
```
Note that this file previous has been named `.install-gnome-themes-cache`. The change in name is due to this feature, because this file can now be used to configure the script.
