### ISSUE TITLE
installing themes broke gnome tweak

### ISSUE THREAD

**Issue by vino3333** [tliron/install-gnome-themes#31]
I followed your instructions to install gnome themes...
https://www.linuxuprising.com/2019/03/install-gnome-themes-script-to-install.html

After selecting a theme to try I can no longer use gnome tweak, Its frozen and I can't select anything! How can I fix this problem? How can I uninstall all the themes and go back to default theme in Fedora 29?

I'll never install any group themes again.

**Comment by tliron** [comment]
Use this command to remove all user-installed themes:

`rm -r ~/.themes`

It would be great if you can find out which theme caused the crash and notify the theme developer!

**Comment by vino3333** [comment]
It was the Paper theme and made it freeze.
Thank you

**Comment by tliron** [comment]
My pleasure, I hope you will open a bug there.
