### ISSUE TITLE
How to uninstall?

### ISSUE THREAD

**Issue by sshsurabhi** [tliron/install-gnome-themes#32]
I installed these themes and I don't face any problem in this process. But, how to uninstall if I don't want them in the future.

**Comment by tliron** [comment]
To uninstall all user themes:
`rm -r ~/.themes`

**Comment by cyfrost** [comment]
> I installed these themes and I don't face any problem in this process. But, how to uninstall if I don't want them in the future.

There is no "installation/uninstallation" process for GNOME themes per se, if a theme structured in a directory _meeting_ the [spec](https://wiki.xfce.org/gnome-theme-package) is placed in the `$XDG_CONFIG_HOME/.themes` directory, it gets picked up as a valid GTK/Shell/Icon theme by tools like GNOME Tweak Tool or `gsettings`.

To "install" a theme,
 
1. download one from freedesktop or gnome-look.org and put it in `$XDG_CONFIG_HOME/.themes` directory.
2. Use either GNOME Tweak Tool or `gsettings` to apply the theme.


To "uninstall" a theme, 

1. first change your theme to something other than the one that you'll be removing now.
2. simply delete the directory of the theme (usually with it's name, ex: `Arc-Dark`).

**Comment by tliron** [comment]
Thanks, @cyfrost, may I include some of your text in the README to help others?

**Comment by cyfrost** [comment]
Sure, I'll be glad :) @tliron
