### ISSUE TITLE
hey tliron FIX THIS f

### ISSUE THREAD

**Issue by meuor** [tliron/install-gnome-themes#34]
`emptyi0r@nakxion:~/install-gnome-themes$ ./install-gnome-themes 
Detected GNOME 3.28, GTK 3.22.
/home/emptyi0r/install-gnome-themes/utils.sh: line 14: /home/emptyi0r/.themes/.install-gnome-themes.log: No such file or directory
install-gnome-themes failed!
/home/emptyi0r/install-gnome-themes/utils.sh: line 14: /home/emptyi0r/.themes/.install-gnome-themes.log: No such file or directory`
file install-gnome-themes

**Comment by tliron** [comment]
I just committed a fix, could you please verify?
