### ISSUE TITLE
Doesn't go past Adapta (stuck on rendering assets)

### ISSUE THREAD

**Issue by tylergale** [tliron/install-gnome-themes#36]
On my Ryzen 1600, 32GB RAM system and using the script, I get 100% CPU usage on all cores, but the rendering of assets for Adapta never finishes (2+ hours of waiting).  I have included what the terminal output looks like (and it never gets past what I have pasted here).

System is running Pop_OS! 19.04 with Kernel 5.0.0-21.  Never had this issue before!

`LOG=/dev/stdout ~/install-gnome-themes/install-gnome-themes
Detected GNOME 3.32, GTK 3.24.
Detected Ubuntu operating system.
Adapta, Adapta-Eta, Adapta-Nokto, Adapta-Nokto-Eta:
  Fetching repository: https://github.com/tista500/Adapta...
Cloning into 'Adapta'...
remote: Enumerating objects: 427, done.
remote: Counting objects: 100% (427/427), done.
remote: Compressing objects: 100% (314/314), done.
remote: Total 427 (delta 241), reused 172 (delta 101), pack-reused 0
Receiving objects: 100% (427/427), 475.13 KiB | 643.00 KiB/s, done.
Resolving deltas: 100% (241/241), done.
  Last updated 9 months ago. 
  Installing... 
  WARNING: Installation takes an especially long time due to rendering of all assets, please be patient! 
configure.ac:14: installing './install-sh'
configure.ac:14: installing './missing'
+ ./configure --enable-parallel --prefix=/tmp/install-gnome-themes/Adapta --disable-cinnamon --disable-xfce --disable-mate --disable-openbox --enable-chrome-legacy
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /usr/bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking whether UID '1000' is supported by ustar format... yes
checking whether GID '1000' is supported by ustar format... yes
checking how to create a ustar tar archive... gnutar
checking whether make supports nested variables... (cached) yes
checking for pkg-config... /usr/bin/pkg-config
checking pkg-config is at least version 0.9.0... yes
checking for GDK_PIXBUF... yes
checking for GLIB... yes
checking for glib-compile-resources... /usr/bin/glib-compile-resources
checking for inkscape... /usr/bin/inkscape
checking for sassc... /usr/bin/sassc
checking for parallel... /usr/bin/parallel
checking for Gnome-Shell SCSS version... 3.26
creating ./gtk/sass/common/_key_colors.scss
checking that generated files are newer than configure... done
configure: creating ./config.status
config.status: creating Makefile
config.status: creating gtk/Makefile
config.status: creating shell/Makefile
config.status: creating wm/Makefile
config.status: creating extra/Makefile

        Adapta Gtk+ Theme 3.95.0
        =================================================================

         prefix:                 /tmp/install-gnome-themes/Adapta
         datarootdir:            ${prefix}/share
         target directories:     ${prefix}/share/themes/Adapta
                                 ${prefix}/share/themes/Adapta-Nokto
                                 ${prefix}/share/themes/Adapta-Eta
                                 ${prefix}/share/themes/Adapta-Nokto-Eta

         glib-compile-resources: /usr/bin/glib-compile-resources
         inkscape:               /usr/bin/inkscape
         sassc:                  /usr/bin/sassc

         parallel-build:         yes (default: no)
         parallel:               /usr/bin/parallel

         selection-color:        #00BCD4 (default: #00BCD4)
         accent-color:           #4DB6AC (default: #4DB6AC)
         suggestion-color:       #009688 (default: #009688)
         destruction-color:      #FF5252 (default: #FF5252)

        -----------------------------------------------------------------
        | Supported Gtk+ Version
        -----------------------------------------------------------------

         Gtk+ 2.0:               always
         Gtk+ 3.20:              always
         Gtk+ 3.22:              always
         Gtk+ 3.24:              always
         Gtk+ 4.0:               no (default: no)

        -----------------------------------------------------------------
        | DE and WM Support
        -----------------------------------------------------------------

         Budgie-Desktop:         always (>= 10.4)
         GNOME:                  yes (SCSS ver. 3.26) (default: yes)
         Cinnamon:               no (default: yes)
         GNOME-Flashback:        yes (default: yes)
         XFce:                   no (default: yes)
         Mate:                   no (default: yes)
         Openbox:                no (default: yes)

        -----------------------------------------------------------------
        | Extra Support
        -----------------------------------------------------------------

         GtkSourceView/Gedit:    always
         Chrome(ium)-legacy:     yes (default: no)
         Plank:                  no (default: no)
         Telegram:               no (default: no)
         Tweetdeck-Colordeck:    no (default: no)

        =================================================================
                                   =>> run 'make' and 'sudo make install'

Making all in gtk
make[1]: Entering directory '/tmp/install-gnome-themes/Adapta/gtk'
/usr/bin/mkdir -p ./gtk-3.20 && \
/usr/bin/mkdir -p ./gtk-3.20-eta && \
/usr/bin/mkdir -p ./gtk-3.20-nokto && \
/usr/bin/mkdir -p ./gtk-3.20-nokto-eta && \
/usr/bin/mkdir -p ./gtk-3.22 && \
/usr/bin/mkdir -p ./gtk-3.22-eta && \
/usr/bin/mkdir -p ./gtk-3.22-nokto && \
/usr/bin/mkdir -p ./gtk-3.22-nokto-eta && \
/usr/bin/mkdir -p ./gtk-3.24 && \
/usr/bin/mkdir -p ./gtk-3.24-eta && \
/usr/bin/mkdir -p ./gtk-3.24-nokto && \
/usr/bin/mkdir -p ./gtk-3.24-nokto-eta && \
/usr/bin/mkdir -p ./asset/assets-gtk2 && \
/usr/bin/mkdir -p ./asset/assets-gtk2/Arrows && \
/usr/bin/mkdir -p ./asset/assets-gtk2/Buttons && \
/usr/bin/mkdir -p ./asset/assets-gtk2/Arrows && \
/usr/bin/mkdir -p ./asset/assets-gtk2/Check-Radio && \
/usr/bin/mkdir -p ./asset/assets-gtk2/Column && \
/usr/bin/mkdir -p ./asset/assets-gtk2/Entry && \
/usr/bin/mkdir -p ./asset/assets-gtk2/Handles && \
/usr/bin/mkdir -p ./asset/assets-gtk2/Lines && \
/usr/bin/mkdir -p ./asset/assets-gtk2/Others && \
/usr/bin/mkdir -p ./asset/assets-gtk2/ProgressBar && \
/usr/bin/mkdir -p ./asset/assets-gtk2/Range && \
/usr/bin/mkdir -p ./asset/assets-gtk2/Scrollbars && \
/usr/bin/mkdir -p ./asset/assets-gtk2/Shadows && \
/usr/bin/mkdir -p ./asset/assets-gtk2/Spin && \
/usr/bin/mkdir -p ./asset/assets-gtk2/Toolbar && \
/usr/bin/mkdir -p ./asset/assets-gtk3
cd ./gtk-2.0 && ./recolor-gtk2.sh
cd ./sass && /usr/bin/parallel --null --no-notice --line-buffer --jobs 100% ::: \
	"/usr/bin/sassc -M -t compact 3.20/gtk.scss ../gtk-3.20/gtk-contained.css" \
	"/usr/bin/sassc -M -t compact 3.20/gtk-dark.scss ../gtk-3.20/gtk-contained-dark.css" \
	"/usr/bin/sassc -M -t compact 3.20/gtk-eta.scss ../gtk-3.20-eta/gtk-contained.css" \
	"/usr/bin/sassc -M -t compact 3.20/gtk-dark-eta.scss ../gtk-3.20-eta/gtk-contained-dark.css" \
	"/usr/bin/sassc -M -t compact 3.22/gtk.scss ../gtk-3.22/gtk-contained.css" \
	"/usr/bin/sassc -M -t compact 3.22/gtk-dark.scss ../gtk-3.22/gtk-contained-dark.css" \
	"/usr/bin/sassc -M -t compact 3.22/gtk-eta.scss ../gtk-3.22-eta/gtk-contained.css" \
	"/usr/bin/sassc -M -t compact 3.22/gtk-dark-eta.scss ../gtk-3.22-eta/gtk-contained-dark.css" \
	"/usr/bin/sassc -M -t compact 3.24/gtk.scss ../gtk-3.24/gtk-contained.css" \
	"/usr/bin/sassc -M -t compact 3.24/gtk-dark.scss ../gtk-3.24/gtk-contained-dark.css" \
	"/usr/bin/sassc -M -t compact 3.24/gtk-eta.scss ../gtk-3.24-eta/gtk-contained.css" \
	"/usr/bin/sassc -M -t compact 3.24/gtk-dark-eta.scss ../gtk-3.24-eta/gtk-contained-dark.css"
compound selectors may no longer be extended.
Consider `@extend ${compound.components.join(', ')}` instead.
See http://bit.ly/ExtendCompound for details.
compound selectors may no longer be extended.
Consider `@extend ${compound.components.join(', ')}` instead.
See http://bit.ly/ExtendCompound for details.
compound selectors may no longer be extended.
Consider `@extend ${compound.components.join(', ')}` instead.
See http://bit.ly/ExtendCompound for details.
compound selectors may no longer be extended.
Consider `@extend ${compound.components.join(', ')}` instead.
See http://bit.ly/ExtendCompound for details.
compound selectors may no longer be extended.
Consider `@extend ${compound.components.join(', ')}` instead.
See http://bit.ly/ExtendCompound for details.
compound selectors may no longer be extended.
Consider `@extend ${compound.components.join(', ')}` instead.
See http://bit.ly/ExtendCompound for details.
compound selectors may no longer be extended.
Consider `@extend ${compound.components.join(', ')}` instead.
See http://bit.ly/ExtendCompound for details.
compound selectors may no longer be extended.
Consider `@extend ${compound.components.join(', ')}` instead.
See http://bit.ly/ExtendCompound for details.
compound selectors may no longer be extended.
Consider `@extend ${compound.components.join(', ')}` instead.
See http://bit.ly/ExtendCompound for details.
compound selectors may no longer be extended.
Consider `@extend ${compound.components.join(', ')}` instead.
See http://bit.ly/ExtendCompound for details.
compound selectors may no longer be extended.
Consider `@extend ${compound.components.join(', ')}` instead.
See http://bit.ly/ExtendCompound for details.
compound selectors may no longer be extended.
Consider `@extend ${compound.components.join(', ')}` instead.
See http://bit.ly/ExtendCompound for details.
`

**Comment by tylergale** [comment]
Commenting out Adapta allows the script to progress completely, including with other themes that render (e.g. Arc).

**Comment by tliron** [comment]
That's odd. It looks like a sassc issue. Are you using the sassc that is bundled with Pop_OS or building it yourself? I just checked on my machine (Fedora 30) and it does render correctly.

BTW, you don't need to comment out the code, in the README here you can see a way to skip certain themes from installing.

**Comment by tylergale** [comment]
This issue can be closed.

I have used your script across a number of installs now and I have never been able to replicate the issue since.
