### ISSUE TITLE
`make` not installed but required in Debian 10

### ISSUE THREAD

**Issue by FuckYouMicrosoftGitHub** [tliron/install-gnome-themes#39]
Hi,

Title says it all, `make` wasn't installed on my system (on a rather fresh install of Debian Buster).
I had ran the install-requirements-debian script.

Thanks.

**Comment by tliron** [comment]
The README does say you need to run that script first.

**Comment by FuckYouMicrosoftGitHub** [comment]
Yes, as I said, I had run the install-requirements-debian script prior to installing a theme.

**Comment by tliron** [comment]
I see. So why did you open an issue? Is there something you suggest we should fix to make this clearer?

**Comment by FuckYouMicrosoftGitHub** [comment]
Add `make` as a pre-requisite otherwise your installation script fails?

**Comment by tliron** [comment]
The script installs `automake`. Are you saying that despite running the script, you did not end up with `make` installed?

**Comment by FuckYouMicrosoftGitHub** [comment]
Exactly, it's not pulled out by its dependencies.
Not a big issue and sorry for not making it very clear since the start.

**Comment by tliron** [comment]
Thanks, I understand now. :)
