### ISSUE TITLE
Don't work with mate 1.18

### ISSUE THREAD

**Issue by Jeremi360** [tliron/install-gnome-themes#4]
Don't work with mate 1.18 it give: ```
line 44: gnome-shell: command don't found
This script only GNOME version 3.18 up to 3.24.
```
Mate from version 1.18 is use fully GTK 3 in version 3.18.

**Comment by tliron** [comment]
The script was specifically designed for GNOME, and many of these themes have GNOME Shell themes included, which are meaningless in Mate. But I see no reason why we can't have it just add nice GTK+ theming support for Mate. I will try to find a way to detect the GTK+ version.

**Comment by tliron** [comment]
I've just added support for detecting GTK (in addition to GNOME). Can you test and tell me if it works for you?

**Comment by Jeremi360** [comment]
Yes! It's works!
