### ISSUE TITLE
Install failed on Ubuntu 20.04

### ISSUE THREAD

**Issue by abd6982** [tliron/install-gnome-themes#47]
Attaching the log here. I have already installed the prerequisites.
[.install-gnome-themes.log](https://github.com/tliron/install-gnome-themes/files/4610734/default.install-gnome-themes.log)

**Comment by tliron** [comment]
This seems to be an issue with the version of sass on Ubuntu 20.04 not working with the Arc Flatabulous theme. I suggest disabling that theme for now using the instructions in the README.

**Comment by abd6982** [comment]
Thanks for the reply @tliron. I found [this](https://github.com/andreisergiu98/arc-flatabulous-theme/issues/45#issuecomment-625254183) comment in one of the issues of the arc-flatabulous-theme repo. It's a workaround for the libsass problem on Ubuntu 20.04. I'll try this out and see if it works, otherwise the only option is to skip this theme for now.
