### ISSUE TITLE
Prompt user to install autoconf and inkscape

### ISSUE THREAD

**Issue by rbreaves** [tliron/install-gnome-themes#48]
Or this needs to be mentioned as dependency in the readme.

Add sassc, and parallel to the list.

**Comment by tliron** [comment]
The README already instructs you to run the install scripts for requirements. Did you miss that?

**Comment by rbreaves** [comment]
I did miss that & see how I missed it too. I usually just skim & scan for gray boxes & assume if the commands for running/installing requirements aren’t in a Gray code box then it’s simply part of the rest of the installer.

Doesn’t make a lot of sense to not include it in the same area imo. Closing ticket.
