### ISSUE TITLE
install-gnome-themes failed! Arc-Flatabulous / Yaru

### ISSUE THREAD

**Issue by alexb3d** [tliron/install-gnome-themes#49]
It gives me error when installing the script with these two themes.
I removed it from the script list and I have no problems with the others.

Please put on the installation page that these requirements must be installed, a person who does not know (like me) will not be able to install the themes. I was able to install it thanks to [linuxuprising](https://www.linuxuprising.com/2019/03/install-gnome-themes-script-to-install.html)

**Comment by tliron** [comment]
Which requirements are missing exactly?

Note that themes break all the time: this script tracks the latest master branch of each theme and specific problems would need to be raised as issues on those repositories.

**Comment by alexb3d** [comment]
It would be the dependencies, I imagine.

Debian / Ubuntu:
`./install-gnome-themes/install-requirements-debian
`
Fedora:
`./install-gnome-themes/install-requirements-fedora`

**Comment by tliron** [comment]
I'm sorry, I don't understand what you are asking me to do. The README tells you to run the install-requirement scripts right at the top. Perhaps you can submit a pull request with changes you think would be helpful?

**Comment by alexb3d** [comment]
Nothing complicated...

1. The Arc-Flatabulous and Yaru themes fail to install.

```
Arc-Flatabulous, Arc-Flatabulous-Dark, Arc-Flatabulous-Darker:
  Fetching repository: https://github.com/andreisergiu98/arc-flatabulous-theme ...
  Last updated hace 3 meses. 
  Installing... 
  WARNING: Installation takes an especially long time due to rendering of all assets, please be patient! 
install-gnome-themes failed! 
```


2. Besides, I asked you to include the dependencies in the installation instructions, in the [Wiki](https://github.com/tliron/install-gnome-themes) it says it doesn't say how. 

Debian / Ubuntu:
./install-gnome-themes/install-requirements-debian
Fedora:
./install-gnome-themes/install-requirements-fedora

**Comment by tliron** [comment]
1. Please disable broken themes according to the instructions in the README.
2. Again, I'm sorry but I don't understand what you are saying. You are saying that I should include the dependencies in the README, but they are already there, with links and instructions.

**Comment by alexb3d** [comment]
1. I did not read the readme, I deleted them directly from the file `install-gnome-themes`

2. If I don't do this `./install-gnome-themes/install-requirements-debian`
 the themes are not installed. Nowhere does it say that it must be done.

**Comment by tliron** [comment]
You are linking directly to the page where everything is explained:

> You need to install the requirements first. See install-requirements-fedora and install-requirements-debian. The Debian script should work for Ubuntu, too.

The page also explains how to disable broken themes. Please read the entire page. Thank you.

**Comment by alexb3d** [comment]
But you do not say how it is installed from the terminal.
You have step by step how to install it from the terminal, but the dependencies do not.

Seriously, is it that hard to understand?

**Comment by tliron** [comment]
I'm sorry @alexb3d , maybe there is a language barrier here. I simply cannot understand what you want me to do. The instructions are right there in the README. Please submit a pull request or otherwise write down what you expect to see in the README that would make thse instruction clearer.

I really thank you and appreciate you trying to improve this project! I apologize that I do not understand.

**Comment by alexb3d** [comment]
Nothing happens, my English is horrible [LOL].
If I can, it is a pleasure to help.
