### ISSUE TITLE
Feature request - add orchis theme

### ISSUE THREAD

**Issue by ChrisLauinger77** [tliron/install-gnome-themes#51]
any chance the orchis theme can be included ?
https://github.com/vinceliuice/Orchis-theme

**Comment by tliron** [comment]
Lovely theme, thanks!

**Comment by ChrisLauinger77** [comment]
U R welcome

**Comment by ChrisLauinger77** [comment]
Also it supports more colors - with no parameter -t it only installs blue
Tip: ./install.sh allows the following options:

-d, --dest DIR          Specify destination directory (Default: /usr/share/themes)
-n, --name NAME         Specify theme name (Default: Orchis)
**-t, --theme VARIANT...  Specify theme color variant(s) [default|purple|pink|red|orange|yellow|green|grey|all] (Default: blue)**
-c, --color VARIANT...  Specify color variant(s) [standard|light|dark] (Default: All variants)
--radio-color           Change radio button checked color to default primary color (Default is Green)
-h, --help              Show help

**Comment by tliron** [comment]
I'm going to go ahead and install all themes ... there are a lot of variants in total.
