### ISSUE TITLE
orchis removed -t all option

### ISSUE THREAD

**Issue by ChrisLauinger77** [tliron/install-gnome-themes#53]
for some reasong -t all was removed in an update 2 days ago :(
commit:
https://github.com/vinceliuice/Orchis-theme/commit/f926439a879f897dfd96ba36d598309d115815fa

**Comment by tliron** [comment]
Thank you! Could you provide a PR?

**Comment by ChrisLauinger77** [comment]
I will try

**Comment by ChrisLauinger77** [comment]
https://github.com/tliron/install-gnome-themes/pull/54
