### ISSUE TITLE
skeuos-gtk failed

### ISSUE THREAD

**Issue by ChrisLauinger77** [tliron/install-gnome-themes#57]
Clone to 'skeuos-gtk' ...
  Last updated in 24 Hours.
  Installing...
  Failed!

probably caused by this commit ?
https://github.com/daniruiz/skeuos-gtk/commit/5eea16309aa681da0eaf3d183b3423ebee14fd23

**Comment by tliron** [comment]
Likely. See the README here for how to view build log. Any suggestion on how to fix this would be appreciated!

**Comment by ChrisLauinger77** [comment]
here is whats in the .install-gnome-themes.log

Fetching repository: https://github.com/daniruiz/skeuos-gtk ...
Cloning into 'skeuos-gtk'...
  Last updated 5 hours ago.
  Installing...
cp: cannot stat 'Skeuos-Black-Dark': No such file or directory
cp: cannot stat 'Skeuos-Black-Light': No such file or directory
cp: cannot stat 'Skeuos-Blue-Dark': No such file or directory
cp: cannot stat 'Skeuos-Blue-Light': No such file or directory
cp: cannot stat 'Skeuos-Brown-Dark': No such file or directory
cp: cannot stat 'Skeuos-Brown-Light': No such file or directory
cp: cannot stat 'Skeuos-Cyan-Dark': No such file or directory
cp: cannot stat 'Skeuos-Cyan-Light': No such file or directory
cp: cannot stat 'Skeuos-Green-Dark': No such file or directory
cp: cannot stat 'Skeuos-Green-Light': No such file or directory
cp: cannot stat 'Skeuos-Grey-Dark': No such file or directory
cp: cannot stat 'Skeuos-Grey-Light': No such file or directory
cp: cannot stat 'Skeuos-Magenta-Dark': No such file or directory
cp: cannot stat 'Skeuos-Magenta-Light': No such file or directory
cp: cannot stat 'Skeuos-Orange-Dark': No such file or directory
cp: cannot stat 'Skeuos-Orange-Light': No such file or directory
cp: cannot stat 'Skeuos-Red-Dark': No such file or directory
cp: cannot stat 'Skeuos-Red-Light': No such file or directory
cp: cannot stat 'Skeuos-Teal-Dark': No such file or directory
cp: cannot stat 'Skeuos-Teal-Light': No such file or directory
cp: cannot stat 'Skeuos-Violet-Dark': No such file or directory
cp: cannot stat 'Skeuos-Violet-Light': No such file or directory
cp: cannot stat 'Skeuos-White-Dark': No such file or directory
cp: cannot stat 'Skeuos-White-Light': No such file or directory
cp: cannot stat 'Skeuos-Yellow-Dark': No such file or directory
cp: cannot stat 'Skeuos-Yellow-Light': No such file or directory
  Failed!

When I check /tmp/install-gnome-themes/
there is a skeuos-gtk subfolder with a themes subfolder inside. 
I guess the "theme-cp" does not expect subfolder themes, does it ?

**Comment by ChrisLauinger77** [comment]
Have you looked in the provided Makefile 

>  install:
> 	mkdir -p $(DESTDIR)$(PREFIX)/share/themes
> 	cp -a $(foreach theme,$(THEMES),themes/$(theme)) $(DESTDIR)$(PREFIX)/share/themes

**Comment by tliron** [comment]
I have not had time to look at all yet. Any chance you can provide a fix?

**Comment by ChrisLauinger77** [comment]
I will have a look

**Comment by ChrisLauinger77** [comment]
I managed to copy partly the theme by adding themes/ to your calls like:

theme-cp github daniruiz skeuos-gtk master \
	themes/Skeuos-Black-Dark \
	themes/Skeuos-Black-Light \
	themes/Skeuos-Blue-Dark \
	themes/Skeuos-Blue-Light \
	themes/Skeuos-Brown-Dark \
	themes/Skeuos-Brown-Light \
	themes/Skeuos-Cyan-Dark \
	themes/Skeuos-Cyan-Light \
	themes/Skeuos-Green-Dark \
	themes/Skeuos-Green-Light \
	themes/Skeuos-Grey-Dark \
	themes/Skeuos-Grey-Light \
	themes/Skeuos-Magenta-Dark \
	themes/Skeuos-Magenta-Light \
	themes/Skeuos-Orange-Dark \
	themes/Skeuos-Orange-Light \
	themes/Skeuos-Red-Dark \
	themes/Skeuos-Red-Light \
	themes/Skeuos-Teal-Dark \
	themes/Skeuos-Teal-Light \
	themes/Skeuos-Violet-Dark \
	themes/Skeuos-Violet-Light \
	themes/Skeuos-White-Dark \
	themes/Skeuos-White-Light \
	themes/Skeuos-Yellow-Dark \
	themes/Skeuos-Yellow-Light

But that is only half what we need.
He has subfolder for the different window managers:
Skeuos-Black-Dark-FullPanel-GNOME_38+36/gnome-shell
Skeuos-Black-Dark-FullPanel-GNOME_40+41/gnome-shell
Skeuos-Black-Dark-GNOME_38+36/gnome-shell
Skeuos-Black-Dark-GNOME_40+41/gnome-shell
Skeuos-Black-Dark-XFWM-HiDPI/xfwm4
Skeuos-Black-Dark-XFWM-xHiDPI/xfwm4
Skeuos-Black-Dark-XFWM/xfwm4

Before the themes are copied we would need to choose one of the redundant ones and copy it to the "main" folder.
Any idea how to manage that elegantly ?
